# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_xFdbhTjWfVjrLPmWYaO6B503f6SiYx
"""

# =========================
# INSTALL LIBRARY
# =========================
!pip install mlflow==2.19.0 -q

# =========================
# IMPORT LIBRARY
# =========================
import pandas as pd
import mlflow
import mlflow.sklearn
import joblib # Added joblib import

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# =========================
# LOAD DATASET
# =========================
df = pd.read_csv("dataset_clean.csv")

print("Dataset berhasil dimuat")
print("Shape awal:", df.shape)

# =========================
# HANDLE MISSING VALUE
# =========================
df.dropna(subset=['sales'], inplace=True)

# =========================
# SAMPLING DATA
# supaya training lebih cepat
# =========================
df = df.sample(n=100000, random_state=42)

print("Shape setelah sampling:", df.shape)

# =========================
# CEK DATA
# =========================
print(df.head())

# =========================
# FEATURE & TARGET
# =========================
X = df.drop("sales", axis=1)
y = df["sales"]

# =========================
# ONE HOT ENCODING
# =========================
categorical_cols = []

if 'store_id' in X.columns:
    categorical_cols.append('store_id')

if 'item_id' in X.columns:
    categorical_cols.append('item_id')

if len(categorical_cols) > 0:
    X = pd.get_dummies(
        X,
        columns=categorical_cols,
        drop_first=True
    )

print("Shape feature:", X.shape)

# =========================
# SPLIT DATA
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Train size:", X_train.shape)
print("Test size :", X_test.shape)

# =========================
# SET MLFLOW
# =========================
mlflow.set_tracking_uri("file:./mlruns")

mlflow.set_experiment("Retail Sales Forecasting")

# =========================
# START RUN
# =========================
with mlflow.start_run():

    # =========================
    # MODEL
    # =========================
    model = RandomForestRegressor(
        n_estimators=10,
        max_depth=10,
        random_state=42,
        n_jobs=-1
    )

    # =========================
    # TRAINING
    # =========================
    model.fit(X_train, y_train)

    # =========================
    # PREDICTION
    # =========================
    y_pred = model.predict(X_test)

    # =========================
    # EVALUATION
    # =========================
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    # =========================
    # LOG PARAMETER
    # =========================
    mlflow.log_param("model_type", "RandomForestRegressor")
    mlflow.log_param("n_estimators", 10)
    mlflow.log_param("max_depth", 10)

    # =========================
    # LOG METRICS
    # =========================
    mlflow.log_metric("MAE", mae)
    mlflow.log_metric("MSE", mse)
    mlflow.log_metric("R2_Score", r2)

    # =========================
    # LOG MODEL
    # =========================
    # Due to a potential ImportError with mlflow.sklearn.log_model in version 2.19.0,
    # we will save the model using joblib and then log it as an artifact.
    joblib.dump(model, "random_forest_model.pkl")
    mlflow.log_artifact("random_forest_model.pkl")
    # mlflow.sklearn.log_model(model, "model") # Original line causing error, commented out

    # =========================
    # OUTPUT
    # =========================
    print("\nTraining selesai!")
    print(f"MAE       : {mae}")
    print(f"MSE       : {mse}")
    print(f"R2 Score  : {r2}")

# =========================
# MENJALANKAN MLFLOW UI
# =========================
print("\nJalankan command berikut di terminal/colab:")
print("mlflow ui")